import test from 'node:test';import assert from 'node:assert/strict';
import {createDemo} from '../demo.mjs';import {evaluateGraph,analyzeGraph} from '../graph.mjs';
import {validateEvidence,collapseEvidence,makeJudgmentEnvelope,publicIPv4,sourceURL,htmlText,digest} from '../evidence.mjs';
const model=()=>createDemo().model;
test('demo root is computed from evidence rather than authored headline',()=>{const m=model();const r=evaluateGraph(m);assert.ok(r.root.range[0]>.28&&r.root.range[0]<.29);assert.ok(r.root.range[1]>.88&&r.root.range[1]<.89)});
test('all presentation changes leave inference identical',()=>{const m=model(),before=evaluateGraph(m);m.ui={expanded:['A1'],selected:'H1',mode:'plain',hiddenDepth:200};assert.deepEqual(evaluateGraph(m),before)});
test('evaluation never mutates graph inputs',()=>{const m=model(),before=JSON.stringify(m);analyzeGraph(m,{overrides:{A1:[.1,.2]}});assert.equal(JSON.stringify(m),before)});
test('same observation copied ten times does not change posterior',()=>{const m=model(),base=evaluateGraph(m).root.range;for(let i=0;i<10;i++)m.evidence[`copy${i}`]={...structuredClone(m.evidence.e1),id:`copy${i}`};assert.deepEqual(evaluateGraph(m).root.range,base)});
test('conflicting claims in a shared cluster cannot be silently selected',()=>{const m=model();m.evidence.copy={...structuredClone(m.evidence.e1),id:'copy',likelihood:{...m.evidence.e1.likelihood,lr:[50,60]}};const r=evaluateGraph(m);assert.equal(r.root.range,null);assert.match(r.nodes.A1.reasons.join(' '),/Conflicting/)});
test('falsified quote withholds affected root',()=>{const m=model();m.evidence.e1.references[0].quote='this quote was invented';assert.equal(evaluateGraph(m).root.range,null)});
test('source tampering is detected',()=>{const m=model();m.sources.s1.text+='tamper';assert.equal(evaluateGraph(m).root.range,null)});
test('source absence is not equivalent to evidence against',()=>{const m=model();delete m.evidence.e1;const r=evaluateGraph(m);assert.equal(r.nodes.A1.status,'prior-only');assert.deepEqual(r.nodes.A1.range,m.nodes.A1.prior)});
test('synthetic numbers are forbidden outside demo',()=>{const m=model();m.demo=false;assert.equal(evaluateGraph(m).root.range,null)});
test('necessary conditions cannot be multiplied into a claim',()=>{const m=model();m.nodes.C0.relation.equivalent=false;assert.equal(evaluateGraph(m).root.range,null)});
test('shared source degrades unjustified independence to bounds',()=>{const m=model();m.nodes.C0.relation.dependence='independent';m.nodes.C0.relation.independenceRationale='Assume independent trials.';m.evidence.e2.references=m.evidence.e1.references;const r=evaluateGraph(m);assert.equal(r.root.rule.dependence,'bounded');assert.ok(r.warnings.length)});
test('prior overrides cannot change derived nodes',()=>{assert.throws(()=>evaluateGraph(model(),{overrides:{C0:[.9,.9]}}),/Cannot override/)});
test('multiple likelihoods need explicit conditional independence',()=>{const m=model();m.evidence.e3={...structuredClone(m.evidence.e1),id:'e3',independenceCluster:'other'};assert.equal(evaluateGraph(m).root.range,null)});
test('descriptive mode suppresses every numeric assessment',()=>{const m=model();m.contract.mode='descriptive';const r=analyzeGraph(m);assert.equal(r.root.range,null);assert.ok(Object.values(r.nodes).every(n=>n.range===null));assert.equal(r.cruxes.length,0)});
test('budget-stopped leaves remain unresolved',()=>{const m=model();m.nodes.A1.atomicity={status:'unresolved',reason:'budget'};assert.equal(evaluateGraph(m).root.range,null)});
test('sensitivity identifies real input changes, not arbitrary constant percentages',()=>{const a=analyzeGraph(model());assert.equal(a.cruxes.length,4);assert.equal(a.grounding.backedInputs,2);assert.ok(a.cruxes[0].span>0);assert.equal(a.nextInvestigations[0].expectedInformationGain,null)});
test('source date after historical cutoff is rejected',()=>{const m=model();m.sources.s1.publishedAt='2026-01-01';assert.throws(()=>validateEvidence(m.evidence.e1,m.sources,{asOf:'2025-01-01',demo:true}),/cutoff/)});
test('negative model judgment weights are rejected',()=>assert.throws(()=>makeJudgmentEnvelope({id:'x',task:'relevance',provider:'p',model:'m',question:'q',options:[{label:'a',probability:-1},{label:'b',probability:2}],sourceIds:[]})));
for(const ip of ['127.0.0.1','10.0.0.1','169.254.169.254','172.31.0.1','192.168.1.1','100.64.0.1','198.18.0.1','203.0.113.1','::1','::ffff:127.0.0.1'])test(`SSRF address blocked: ${ip}`,()=>assert.equal(publicIPv4(ip),false));
for(const url of ['http://example.com','https://user:pass@example.com','https://example.com:9000','https://127.1','https://2130706433','https://[::1]','file:///etc/passwd','https://secret.local'])test(`SSRF URL blocked: ${url}`,()=>assert.throws(()=>sourceURL(url)));
test('public HTTPS source URL accepted',()=>assert.equal(sourceURL('https://example.com/path#fragment').href,'https://example.com/path'));
test('HTML source extraction strips active markup',()=>{const text=htmlText('<h1>Hello &amp; world</h1><script>steal()</script><style>bad</style><p>&#65; &nbsp; test</p>');assert.equal(text,'Hello & world A test')});
