import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp, rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {auditHash, canonicalJSON} from '../store.mjs';
import {digest} from '../evidence.mjs';
import {options, packet, question, validateContract, makeBody, validateResponse} from '../scale/contracts.mjs';
import {ScaleStore} from '../scale/store.mjs';
import {runCampaign, JevBatchClient, retryDelay, RateGate} from '../scale/runner.mjs';
import {syntheticManifest, SyntheticClient} from '../scale/synthetic.mjs';
import {selectReview, reviewCampaign} from '../scale/review.mjs';
import {composeReviewed} from '../scale/compose.mjs';

async function fixture(t) {
  const dir = await mkdtemp(join(tmpdir(), 'veracity-scale-test-')), store = await new ScaleStore(dir).init();
  t.after(async () => { await store.close(); await rm(dir, {recursive: true, force: true}); }); return store;
}
function one() { const m = syntheticManifest(1), p = packet(m.contract, m.packets[0]); return {m, p, q: question([...m.tasks][0], p.hash)}; }
function response(body, p = .8) { return {model: body.model, answers: Object.fromEntries(Object.keys(body.questions).map(k => [k, {type:'noul', noul:p}])), usage:{input_tokens:123,output_tokens:1}}; }

for (const [name, value] of [['negative questions',{maxQuestions:-1}], ['too many questions',{maxQuestions:100001}], ['fraction concurrency',{concurrency:1.5}], ['zero cost',{maxJevUSD:0}], ['NaN price',{inputUSDPerMillion:NaN}], ['negative sample',{randomReviewRate:-1}], ['unknown option',{pretend:true}]]) {
  test(`scale options reject ${name}`, () => assert.throws(() => options(value)));
}
test('probability campaigns do not score descriptive/value questions', () => assert.throws(() => validateContract({mode:'descriptive',wording:'Which choice is best?',scope:'x',asOf:new Date().toISOString()}), /empirical/));
test('source digest mismatch is rejected', () => { const {m}=one();m.packets[0].sources[0].text+='tamper';assert.throws(()=>packet(m.contract,m.packets[0]),/integrity/); });
test('source publication cutoff is enforced', () => { const {m}=one();m.packets[0].sources[0].publishedAt='2027-01-01';assert.throws(()=>packet(m.contract,m.packets[0]),/cutoff/); });
test('state packing measures UTF-8 bytes, not characters', () => { const {m}=one();const s=m.packets[0].sources[0];s.text='測'.repeat(9000);s.sha256=digest(s.text);assert.throws(()=>packet(m.contract,m.packets[0]),/too large/); });
test('missing factual resolution criteria are rejected',()=>{const {p}=one();assert.throws(()=>question({proposition:'x'},p.hash),/falsifier/);});
test('batch preserves shared context and unique question IDs',()=>{const {q,p}=one();const b=makeBody('jev-1.13.0',p,[q]);assert.equal(Object.keys(b.body.questions).length,1);assert.equal(b.body.state,p.state);assert.ok(b.units>Buffer.byteLength(canonicalJSON(b.body)));});
test('moving aliases cannot enter a batch',()=>{const{q,p}=one();assert.throws(()=>makeBody('jev-latest',p,[q]),/Pin/);});
for (const [name, mutate] of [['missing answer',r=>r.answers={}],['unexpected answer',r=>r.answers.x={type:'noul',noul:.5}],['wrong version',r=>r.model='jev-1.14.0'],['missing usage',r=>delete r.usage],['bad type',r=>Object.values(r.answers)[0].type='score'],['NaN probability',r=>Object.values(r.answers)[0].noul=NaN],['negative tokens',r=>r.usage.input_tokens=-1]]) {
  test(`batch withholds ${name}`,()=>{const{q,p}=one();const {body}=makeBody('jev-1.13.0',p,[q]);const r=response(body);mutate(r);assert.throws(()=>validateResponse(r,body));});
}
test('zero and one remain valid Noul values',()=>{const{q,p}=one();const{body}=makeBody('jev-1.13.0',p,[q]);for(const x of[0,1])assert.equal(validateResponse(response(body,x),body).answers[q.id].noul,x);});
test('Retry-After seconds and dates are honored',()=>{assert.equal(retryDelay('7',0),7000);assert.equal(retryDelay('Thu, 01 Jan 1970 00:00:10 GMT',0,0),10000);assert.equal(retryDelay(null,2,0,()=>0),2000);});
test('rate gate paces both request and token reservations',async()=>{let now=0;const delays=[];const gate=new RateGate({requestsPerMinute:60,inputUnitsPerSecond:1000},{clock:()=>now,wait:async ms=>{delays.push(ms);now+=ms;}});await Promise.all([gate.acquire(500),gate.acquire(500),gate.acquire(500)]);assert.deepEqual(delays,[1000,1000]);});
test('batch exceeding per-second dispatch allocation fails closed',async()=>{const g=new RateGate({requestsPerMinute:60,inputUnitsPerSecond:1000});await assert.rejects(g.acquire(1001),/larger/);});
test('Jev real adapter sends multi-question Noul and no key in JSON',async()=>{const{q,p}=one();const{body}=makeBody('jev-1.13.0',p,[q]);let sent;const c=new JevBatchClient({key:'secret-not-a-real-key',fetchImpl:async(url,r)=>{sent={url,...r};return new Response(JSON.stringify(response(body)),{headers:{'x-request-id':'req1'}});}});const r=await c.send(body,{timeoutMs:1000});assert.equal(r.requestId,'req1');assert.equal(sent.headers.Authorization,'Bearer secret-not-a-real-key');assert.equal(sent.body.includes('secret-not-a-real-key'),false);assert.equal(sent.redirect,'error');});
test('TypeSafe 529 is retryable',async()=>{const c=new JevBatchClient({key:'x',fetchImpl:async()=>new Response('overloaded',{status:529,headers:{'retry-after':'2'}})});await assert.rejects(c.send({model:c.model},{timeoutMs:1000}),e=>e.retryable&&e.retryAfter==='2');});
test('TypeSafe auth failure is not automatically retried',async()=>{const c=new JevBatchClient({key:'x',fetchImpl:async()=>new Response('bad key',{status:401})});await assert.rejects(c.send({model:c.model},{timeoutMs:1000}),e=>e.retryable===false);});
test('manifest rejects synthetic evidence in a live campaign',async t=>{const s=await fixture(t);assert.throws(()=>s.create({...syntheticManifest(1),simulation:false}),/Synthetic/);});
test('1000 tasks actually batch, persist, page, and rerun through cache',async t=>{const s=await fixture(t);const r=s.create(syntheticManifest(1000));const c=new SyntheticClient();const done=await runCampaign(s,r.id,{client:c,planHash:r.planHash});assert.equal(done.counts.completed,1000);assert.equal(done.status,'completed');assert.equal(c.calls,100);const p=s.page(r.id,{limit:7});assert.equal(p.items.length,7);assert.equal(p.next,6);assert.equal(s.page(r.id,{after:p.next,limit:7}).items[0].seq,7);const fresh=s.create(syntheticManifest(1000));const client=new SyntheticClient();const cached=await runCampaign(s,fresh.id,{client,planHash:fresh.planHash});assert.equal(client.calls,0);assert.equal(cached.cacheHits,100);assert.equal(cached.usage.requests,0);});
test('one changed packet invalidates only affected batches',async t=>{const s=await fixture(t);let r=s.create(syntheticManifest(1000));await runCampaign(s,r.id,{client:new SyntheticClient(),planHash:r.planHash});r=s.create(syntheticManifest(1000,0));const c=new SyntheticClient();await runCampaign(s,r.id,{client:c,planHash:r.planHash});assert.equal(c.calls,1);});
test('exact semantic duplicates count once and preserve higher review priority',async t=>{const s=await fixture(t),m=syntheticManifest(1),q=[...m.tasks][0];const r=s.create({...m,tasks:[{...q,priority:'normal'},{...q,priority:'critical'}]});assert.equal(r.total,1);assert.equal(r.duplicateQuestions,1);assert.equal(s.page(r.id).items[0].priority,'critical');});
test('invalid imports roll back all run/task records',async t=>{const s=await fixture(t);const m=syntheticManifest(2),ts=[...m.tasks];ts[1].packetId='missing';assert.throws(()=>s.create({...m,tasks:ts}));assert.equal(s.list().length,0);assert.equal(s.sql('select count(*) n from tasks').get().n,0);});
test('budget reserves across concurrent workers before dispatch',async t=>{const s=await fixture(t),r=s.create({...syntheticManifest(100),limits:{maxRequests:1,concurrency:4}}),c=new SyntheticClient();const result=await runCampaign(s,r.id,{client:c,planHash:r.planHash});assert.equal(result.status,'paused');assert.equal(result.usage.requests,1);assert.ok(c.calls<=1);});
test('retries consume a fresh reservation and preserve unknown billing',async t=>{const s=await fixture(t),r=s.create(syntheticManifest(1)),c=new SyntheticClient();const send=c.send.bind(c);let attempt=0;c.send=async(...args)=>{if(attempt++===0){const e=new Error('temporary');e.retryable=true;e.retryAfter='0';throw e;}return send(...args);};const done=await runCampaign(s,r.id,{client:c,planHash:r.planHash,wait:async()=>{}});assert.equal(done.counts.completed,1);assert.equal(done.usage.requests,2);assert.equal(done.usage.unknownAttempts,1);});
test('invalid response pauses and is never partially committed or cached',async t=>{const s=await fixture(t),r=s.create(syntheticManifest(1)),c=new SyntheticClient();c.send=async body=>({response:{...response(body),answers:{}}});const done=await runCampaign(s,r.id,{client:c,planHash:r.planHash});assert.equal(done.status,'paused');assert.equal(done.counts.completed,undefined);assert.equal(s.sql('select count(*) n from cache').get().n,0);assert.equal(done.usage.reportedInputTokens,123);});
test('provider namespace protects real runs from synthetic cache/results',async t=>{const s=await fixture(t),r=s.create(syntheticManifest(1)),c=new SyntheticClient();c.namespace='typesafe-live';await assert.rejects(runCampaign(s,r.id,{client:c,planHash:r.planHash}),/namespace/);});
test('cache integrity corruption is detected',async t=>{const s=await fixture(t),r=s.create(syntheticManifest(1));await runCampaign(s,r.id,{client:new SyntheticClient(),planHash:r.planHash});s.sql("UPDATE cache SET response='{}'").run();const next=s.create(syntheticManifest(1));const done=await runCampaign(s,next.id,{client:new SyntheticClient(),planHash:next.planHash});assert.equal(done.status,'paused');assert.match(done.error,/integrity/);});
test('cancellation retains completed batches and stops new dispatch',async t=>{const s=await fixture(t),r=s.create(syntheticManifest(1000)),c=new SyntheticClient(),control=new AbortController();const send=c.send.bind(c);let ordinal=0;c.send=async(...args)=>{const current=++ordinal;const r=await send(...args);if(current===5){const e=new Error('Cancelled');e.code='CANCELLED';control.abort(e);}return r;};const result=await runCampaign(s,r.id,{client:c,signal:control.signal,planHash:r.planHash});assert.equal(result.status,'cancelled');assert.ok(result.usage.requests<r.batches);assert.ok((result.counts.pending||0)>0);});
test('pausing and resuming does not re-dispatch completed batches',async t=>{const s=await fixture(t),r=s.create(syntheticManifest(1000)),c=new SyntheticClient(),control=new AbortController();const send=c.send.bind(c);c.send=async(...args)=>{if(c.calls===4)control.abort(new Error('Pause'));return send(...args);};const result=await runCampaign(s,r.id,{client:c,signal:control.signal,planHash:r.planHash});assert.equal(result.status,'paused');const completed=result.counts.completed||0;const next=new SyntheticClient();const done=await runCampaign(s,r.id,{client:next,planHash:r.planHash});assert.equal(done.counts.completed,1000);assert.ok(next.calls<r.batches || completed===0);});
test('plan hash must be approved exactly',async t=>{const s=await fixture(t),r=s.create(syntheticManifest(1));await assert.rejects(runCampaign(s,r.id,{client:new SyntheticClient(),planHash:'wrong'}),/Plan changed/);});
test('random review allocation includes confident answers and leaves excess pending',async t=>{const s=await fixture(t),r=s.create(syntheticManifest(1000)),c=new SyntheticClient();c.send=async body=>({response:response(body,.99)});await runCampaign(s,r.id,{client:c,planHash:r.planHash});const selection=selectReview(s,r.id,{limit:12,randomRate:1});assert.equal(selection.selected.length,12);assert.ok(selection.selected.some(x=>x.reasons[0].includes('random')));assert.equal(selection.unreviewedAfterSelection,988);assert.deepEqual(selection.selected.map(x=>x.task.id),selectReview(s,r.id,{limit:12,randomRate:1}).selected.map(x=>x.task.id));});
test('review does not change probabilities or declare calibration',async t=>{const s=await fixture(t),r=s.create({...syntheticManifest(2),limits:{maxReview:2}});await runCampaign(s,r.id,{client:new SyntheticClient(),planHash:r.planHash});const before=s.page(r.id).items.map(x=>x.probability);const provider={configured:true,simulation:true,model:'mock-orchestrator',json:async(_t,_p,input)=>({id:input.task.id,status:'accepted',reason:'Reviewed fixture semantics; not empirically calibrated.'})};await reviewCampaign(s,r.id,provider);const after=s.page(r.id).items;assert.deepEqual(after.map(x=>x.probability),before);assert.ok(after.every(x=>x.calibration==='not-evaluated'&&x.review.status==='accepted'));});
test('review rejects returned IDs not in the requested task',async t=>{const s=await fixture(t),r=s.create(syntheticManifest(1));await runCampaign(s,r.id,{client:new SyntheticClient(),planHash:r.planHash});await assert.rejects(reviewCampaign(s,r.id,{configured:true,simulation:true,model:'mock',json:async()=>({id:'wrong',status:'accepted',reason:'Wrong task result.'})}),/match/);});
test('unreviewed estimates cannot enter the composition bridge',async t=>{const s=await fixture(t),r=s.create(syntheticManifest(1));await runCampaign(s,r.id,{client:new SyntheticClient(),planHash:r.planHash});const task=s.page(r.id).items[0];assert.throws(()=>composeReviewed(s,r.id,{rootId:'A',nodes:[{id:'A',kind:'estimate',taskId:task.id}]}),/reviewed/);});
test('reviewed probabilities compose without reapplying their evidence',async t=>{const s=await fixture(t),m=syntheticManifest(2),tasks=[...m.tasks];tasks[1].packetId=tasks[0].packetId;const r=s.create({...m,tasks});const c=new SyntheticClient();c.send=async body=>({response:response(body,.8)});await runCampaign(s,r.id,{client:c,planHash:r.planHash});const ts=s.page(r.id).items;s.saveReviews(r.id,ts.map(t=>({id:t.id,status:'accepted',reason:'Explicitly reviewed test estimates.'})),{model:'fixture'});const graph={rootId:'R',nodes:[{id:'R',kind:'and',children:['A','B'],equivalent:true,rationale:'The root means exactly both propositions hold.',text:'Both propositions hold',independent:true,independenceRationale:'This asserted independence is intentionally checked.'},...ts.map((t,i)=>({id:i?'B':'A',kind:'estimate',taskId:t.id}))]};const result=composeReviewed(s,r.id,graph);assert.ok(Math.abs(result.root.range[0]-.6)<1e-10);assert.equal(result.root.range[1],.8);assert.match(result.warnings.join(''),/shared/);graph.nodes[1].prior=[.2,.2];assert.throws(()=>composeReviewed(s,r.id,graph),/updated again/);});
