import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createApplication} from '../server.mjs';import {createDemo} from '../demo.mjs';import {AgentRegistry} from '../agents.mjs';
async function setup(t,opts={}){const dir=await mkdtemp(join(tmpdir(),'veracity-api-'));const app=await createApplication({directory:dir,port:0,configured:false,...opts});const address=await app.listen(),base=`http://127.0.0.1:${address.port}`;t.after(async()=>{await app.close();await rm(dir,{recursive:true,force:true})});const call=async(path,body,headers={})=>{const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',Origin:base,...headers},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,headers:r.headers,data:await r.json()}};return {app,base,call};}
test('home is the real app and security headers are present',async t=>{const {base}=await setup(t);const r=await fetch(base);assert.equal(r.status,200);assert.match(await r.text(),/app.mjs/);assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.equal(r.headers.get('x-content-type-options'),'nosniff')});
test('missing provider returns 503 and creates no fake assessment',async t=>{const {call}=await setup(t);const r=await call('/api/assessments',{question:'Is this controversial claim true?'});assert.equal(r.status,503);assert.equal(r.data.code,'PROVIDER_UNCONFIGURED');assert.equal((await call('/api/assessments')).data.assessments.length,0)});
test('demo creates a clearly labeled, computed, persistent assessment',async t=>{const {call}=await setup(t);const a=(await call('/api/demo',{})).data;assert.equal(a.kind,'demo');assert.equal(a.model.demo,true);assert.ok(a.analysis.root.range[1]>.88);const b=(await call(`/api/assessments/${a.id}`)).data;assert.equal(b.id,a.id);assert.equal(b.snapshots.length,1)});
test('what-if saves a new scenario and leaves original unchanged',async t=>{const {call}=await setup(t);const a=(await call('/api/demo',{})).data;const s=await call(`/api/assessments/${a.id}/scenario`,{expectedRevision:a.revision,overrides:{A1:[.1,.2]}});assert.equal(s.status,201);assert.notEqual(s.data.id,a.id);assert.equal(s.data.parentId,a.id);assert.notDeepEqual(s.data.analysis.root.range,a.analysis.root.range);const original=(await call(`/api/assessments/${a.id}`)).data;assert.deepEqual(original.model,a.model);assert.equal(original.revision,1)});
test('stale scenario write is rejected with 409',async t=>{const {call}=await setup(t);const a=(await call('/api/demo',{})).data;assert.equal((await call(`/api/assessments/${a.id}/scenario`,{expectedRevision:0,overrides:{A1:[.1,.2]}})).status,409)});
test('unknown input IDs are rejected',async t=>{const {call}=await setup(t);const a=(await call('/api/demo',{})).data;assert.equal((await call(`/api/assessments/${a.id}/scenario`,{expectedRevision:1,overrides:{FAKE:[.1,.2]}})).status,422)});
test('user evidence is validated, recomputed and snapshotted',async t=>{const {call}=await setup(t);const a=(await call('/api/demo',{})).data;const quote='A second controlled run failed the threshold.';const r=await call(`/api/assessments/${a.id}/evidence`,{expectedRevision:1,nodeId:'A1',title:'User test record',text:`User-provided fixture record. ${quote}`,quote,cluster:'synthetic-errors',lr:[.2,.4],rationale:'Illustrative adverse result is less likely under passing than failing.'});assert.equal(r.status,200);assert.equal(r.data.revision,2);assert.equal(r.data.snapshots.length,2);assert.ok(r.data.analysis.root.range[0]<a.analysis.root.range[0]);assert.equal(Object.keys(r.data.model.evidence).length,2)});
test('invented quote cannot be saved to evidence ledger',async t=>{const {call}=await setup(t);const a=(await call('/api/demo',{})).data;const r=await call(`/api/assessments/${a.id}/evidence`,{expectedRevision:1,nodeId:'A1',title:'Test',text:'This source contains only this exact sentence.',quote:'A nonexistent quotation.',cluster:'synthetic-errors',lr:[.2,.4],rationale:'Some sufficiently long likelihood rationale.'});assert.equal(r.status,422);assert.equal((await call(`/api/assessments/${a.id}`)).data.revision,1)});
test('cross-origin writes rejected',async t=>{const {call}=await setup(t);assert.equal((await call('/api/demo',{}, {Origin:'https://evil.example'})).status,403)});
test('data and server files are never statically served',async t=>{const {base}=await setup(t);for(const path of ['/server.mjs','/.data','/.env','/../store.mjs'])assert.equal((await fetch(base+path)).status,404)});
test('locked API requires valid token; Unicode token cannot cause a timing error',async t=>{const token='a'.repeat(32),{call}=await setup(t,{accessToken:token});assert.equal((await call('/api/config')).status,401);assert.equal((await call('/api/login',{token:'é'.repeat(32)})).status,401);const login=await call('/api/login',{token});assert.equal(login.status,200);assert.match(login.headers.get('set-cookie'),/HttpOnly/);assert.match(login.headers.get('set-cookie'),/SameSite=Strict/);const cookie=login.headers.get('set-cookie').split(';')[0];const c=await call('/api/config',undefined,{Cookie:cookie});assert.equal(c.status,200);assert.ok(!JSON.stringify(c.data).includes(token))});
test('unsafe nonloopback configuration is rejected before startup',async()=>{await assert.rejects(()=>createApplication({host:'0.0.0.0',port:0,accessToken:'',publicOrigin:''}),e=>e.code==='INSECURE_CONFIG')});
test('export has attachment headers and a reproducible model hash',async t=>{const {call}=await setup(t);const a=(await call('/api/demo',{})).data;const e=await call(`/api/assessments/${a.id}/export`);assert.match(e.headers.get('content-disposition'),/attachment/);assert.equal(e.data.snapshots[0].modelHash.length,64)});
test('idempotent research submission creates one run',async t=>{let calls=0;const runner=async({signal})=>{calls++;await new Promise((resolve,reject)=>{signal.addEventListener('abort',()=>reject(signal.reason),{once:true})});};const {call}=await setup(t,{configured:true,runner});const headers={'Idempotency-Key':'same-request-123'};const rs=await Promise.all([call('/api/assessments',{question:'Does this request run only once?'},headers),call('/api/assessments',{question:'Does this request run only once?'},headers)]);assert.equal(rs[0].status,202);assert.equal(rs[0].data.id,rs[1].data.id);assert.equal(calls,1)});
test('capacity is enforced for simultaneous distinct requests',async t=>{const runner=async({signal})=>new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(signal.reason),{once:true}));const {call}=await setup(t,{configured:true,runner,maxRunning:1});const rs=await Promise.all([call('/api/assessments',{question:'First test question?'}),call('/api/assessments',{question:'Second test question?'})]);assert.deepEqual(rs.map(r=>r.status).sort(),[202,429])});
test('cancel request persists cancellation rather than claiming completion',async t=>{const runner=async({signal})=>new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(signal.reason),{once:true}));const {call}=await setup(t,{configured:true,runner});const a=(await call('/api/assessments',{question:'Can this job be cancelled?'})).data;assert.equal((await call(`/api/assessments/${a.id}/cancel`,{})).status,202);let final;for(let i=0;i<20;i++){final=(await call(`/api/assessments/${a.id}`)).data;if(final.status==='cancelled')break;await new Promise(r=>setTimeout(r,10))}assert.equal(final.status,'cancelled');assert.equal(final.analysis,undefined)});
test('invalid public origin is rejected before a store is opened',async()=>{await assert.rejects(()=>createApplication({publicOrigin:'https://example.org/path',accessToken:'a'.repeat(32)}),e=>e.code==='INSECURE_CONFIG')});

test('named harness agents can be selected per research run and are persisted',async t=>{
  const registry=new AgentRegistry({config:{roles:{orchestrator:'strong',worker:'grunt'},agents:{
    strong:{driver:'command',command:[process.execPath,'unused-strong.mjs'],model:'strong-model',capabilities:{search:false}},
    grunt:{driver:'command',command:[process.execPath,'unused-grunt.mjs'],model:'grunt-model',capabilities:{search:true}}
  }}});
  let received;
  const runner=async args=>{received=args;await new Promise((resolve,reject)=>args.signal.addEventListener('abort',()=>reject(args.signal.reason),{once:true}));};
  const {call}=await setup(t,{configured:undefined,agentRegistry:registry,runner});
  const cfg=(await call('/api/config')).data;
  assert.deepEqual(cfg.agents.defaults,{orchestrator:'strong',worker:'grunt'});
  assert.equal(JSON.stringify(cfg).includes('unused-strong.mjs'),false);
  const created=(await call('/api/assessments',{question:'Does this harness-selected investigation preserve its agent roles?',orchestratorAgent:'strong',workerAgent:'grunt'})).data;
  for(let i=0;i<20&&!received;i++)await new Promise(r=>setTimeout(r,5));
  assert.equal(received.orchestratorAgent,'strong');assert.equal(received.workerAgent,'grunt');
  const saved=(await call('/api/assessments/'+created.id)).data;
  assert.deepEqual(saved.agents,{orchestrator:'strong',worker:'grunt'});
  await call('/api/assessments/'+created.id+'/cancel',{});
});
