import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,writeFile,stat} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {AuditStore,auditHash,canonicalJSON} from '../store.mjs';
async function setup(t){const dir=await mkdtemp(join(tmpdir(),'veracity-store-'));const store=await new AuditStore(dir).init();t.after(async()=>{await store.close();await rm(dir,{recursive:true,force:true})});return {store,dir}}
test('canonical hashes do not depend on object property order',()=>assert.equal(auditHash({b:2,a:1}),auditHash({a:1,b:2})));
test('nonfinite numbers cannot enter audit snapshots',()=>assert.throws(()=>canonicalJSON({x:NaN})));
test('store persists and reads integrity-checked records',async t=>{const {store}=await setup(t);const a=await store.create({question:'test',status:'ready'});assert.deepEqual(await store.get(a.id),a)});
test('optimistic concurrency permits only one writer at a revision',async t=>{const {store}=await setup(t);const a=await store.create({question:'test',status:'ready'});const outcomes=await Promise.allSettled(Array.from({length:12},(_,i)=>store.update(a.id,1,x=>({...x,value:i}))));assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);assert.equal((await store.get(a.id)).revision,2);assert.ok(outcomes.filter(x=>x.status==='rejected').every(x=>x.reason.code==='REVISION_CONFLICT'))});
test('corrupt storage is detected instead of loaded as an assessment',async t=>{const {store,dir}=await setup(t);const a=await store.create({question:'test',status:'ready'});const path=join(dir,`${a.id}.json`),raw=JSON.parse(await readFile(path,'utf8'));raw.document.question='tampered';await writeFile(path,JSON.stringify(raw));await assert.rejects(()=>store.get(a.id),e=>e.code==='STORE_INTEGRITY')});
test('data files are owner-only readable',async t=>{const {store,dir}=await setup(t);const a=await store.create({question:'test',status:'ready'});assert.equal((await stat(join(dir,`${a.id}.json`))).mode&0o777,0o600)});
test('path traversal is rejected',async t=>{const {store}=await setup(t);await assert.rejects(()=>store.get('../../etc/passwd'),e=>e.code==='NOT_FOUND')});
test('single writer lock prevents two processes using the same store',async t=>{const {dir}=await setup(t);await assert.rejects(()=>new AuditStore(dir).init(),e=>e.code==='STORE_LOCKED')});
test('interrupted research is identified on reopening',async t=>{const dir=await mkdtemp(join(tmpdir(),'veracity-restart-'));const a=await new AuditStore(dir).init();const item=await a.create({question:'test',status:'running'});await a.close();const b=await new AuditStore(dir).init();t.after(async()=>{await b.close();await rm(dir,{recursive:true,force:true})});assert.equal((await b.get(item.id)).status,'interrupted')});
