"""Offline UI checks using records generated by the running HTTP service.
Browser networking is not used. This is not a substitute for full browser/server E2E.
Requires Python Playwright + Chromium. Set VERACITY_QA_URL / VERACITY_QA_OUTPUT.
"""
import json, os, re, urllib.request
from pathlib import Path
from playwright.sync_api import sync_playwright
root = Path(__file__).resolve().parent.parent
out = Path(os.environ.get('VERACITY_QA_OUTPUT','/mnt/data')); out.mkdir(parents=True, exist_ok=True)
base = os.environ.get('VERACITY_QA_URL','http://127.0.0.1:8787')
def api(path, body=None):
    request=urllib.request.Request(base+path,data=None if body is None else json.dumps(body).encode(),headers={'Content-Type':'application/json'})
    with urllib.request.urlopen(request) as response: return json.load(response)
config=api('/api/config')
original=api('/api/demo',{})
scenario=api('/api/assessments/'+original['id']+'/scenario',{'expectedRevision':original['revision'],'overrides':{'A1':[.1,.2]}})
cluster=next(e['independenceCluster'] for e in scenario['model']['evidence'].values() if 'A1' in e['targetNodeIds'])
evidence={'nodeId':'A1','title':'Browser QA source','text':'The synthetic follow-up reported a failure under the same controlled test conditions.','quote':'The synthetic follow-up reported a failure','cluster':cluster,'lr':[.2,.4],'rationale':'A fictional browser-test likelihood range for a contrary observation; not empirical calibration.','expectedRevision':scenario['revision']}
updated=api('/api/assessments/'+scenario['id']+'/evidence',evidence)
assert api('/api/assessments/'+original['id'])['model']['nodes']['A1']['prior']==[.6,.8]
pack={'config':config,'original':original,'scenario':scenario,'updated':updated,'history':api('/api/assessments')}
html=(root/'public/index.html').read_text()
html=re.sub(r'<link rel="stylesheet"[^>]+>|<script type="module"[^>]+></script>','',html)
html=html.replace('</head>','<style>'+(root/'public/styles.css').read_text()+'</style></head>')
script=(root/'public/app.mjs').read_text()
shim='''() => {
window.__shown = null; history.replaceState = (_a,_b,url) => {window.__shown=url;};
window.fetch = async (path, opts={}) => {
 const p=window.__pack;let value;
 if(path==='/api/config') value=p.config;
 else if(path==='/api/demo') value=p.original;
 else if(path==='/api/assessments') value=p.history;
 else if(path.endsWith('/scenario')) {value=p.scenario;window.__scenarioRequest=JSON.parse(opts.body);}
 else if(path.endsWith('/evidence')) {value=p.updated;window.__evidenceRequest=JSON.parse(opts.body);}
 else if(path.endsWith(p.original.id))value=p.original;
 else if(path.endsWith(p.scenario.id))value=p.updated;
 else throw Error('Unexpected offline request: '+path);
 return new Response(JSON.stringify(value),{status:200,headers:{'Content-Type':'application/json'}});
};
}'''
checks=[];errors=[]
with sync_playwright() as pw:
 browser=pw.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),headless=True,args=['--no-sandbox'])
 def load(width,height):
  page=browser.new_page(viewport={'width':width,'height':height},device_scale_factor=1)
  page.on('pageerror',lambda e:errors.append(str(e)))
  page.set_content(html)
  page.evaluate('(p)=>window.__pack=p',pack)
  page.evaluate(shim)
  page.add_script_tag(content='(async()=>{'+script+'})()')
  page.locator('#demo-button').wait_for()
  return page
 page=load(1440,1000)
 page.screenshot(path=str(out/'veracity-v2-desktop-home.png'),full_page=True)
 checks.append('Offline home renders actual application, honest provider status')
 page.locator('#demo-button').click();page.locator('.overview').wait_for()
 assert '29%–88%' in page.locator('.overview').inner_text()
 page.screenshot(path=str(out/'veracity-v2-desktop.png'),full_page=True)
 checks.append('Worked example renders the server-computed credence and explicit synthetic label')
 page.locator('[data-node="A1"]').click();page.locator('#scenario-form').wait_for()
 page.locator('#scenario-form [name="low"]').fill('0.1');page.locator('#scenario-form [name="high"]').fill('0.2')
 page.locator('#scenario-form button').click();page.wait_for_function('window.__shown.includes(window.__pack.scenario.id)')
 assert page.evaluate('window.__scenarioRequest.overrides.A1')==[.1,.2]
 assert page.locator('.overview .range').inner_text()!='29%–88%'
 checks.append('What-if UI sends expected prior overrides and renders separate computed scenario')
 page.locator('#history-button').click();page.locator('#history-dialog').wait_for(state='visible');page.locator('[data-close="history-dialog"]').click()
 page.get_by_role('tab',name='Change history').click();page.get_by_role('tab',name='Change history').press('ArrowRight')
 assert page.get_by_role('tab',name='Audit notes').get_attribute('aria-selected')=='true'
 checks.append('Saved-research dialog and keyboard tab navigation work')
 with page.expect_download() as dl: page.locator('[data-action="export"]').click()
 assert json.loads(Path(dl.value.path()).read_text())['id']==scenario['id']
 checks.append('JSON export contains the displayed scenario')
 page.locator('[data-action="add-evidence"]').click();page.locator('#evidence-dialog').wait_for(state='visible');page.locator('#evidence-node').select_option('A1')
 form=page.locator('#evidence-form')
 for k in ['title','text','quote','cluster','rationale']:form.locator('[name="'+k+'"]').fill(evidence[k])
 form.locator('[name="lrLow"]').fill('0.2');form.locator('[name="lrHigh"]').fill('0.4');form.locator('button[type="submit"]').click()
 page.locator('#evidence-dialog').wait_for(state='hidden')
 assert page.evaluate('window.__evidenceRequest.lr')==[.2,.4]
 assert 'Browser QA source' in page.locator('#detail-panel').inner_text()
 checks.append('Evidence form sends disclosed assumptions and renders updated evidence record')
 assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
 mobile=load(390,844);mobile.locator('#demo-button').click();mobile.locator('.overview').wait_for()
 assert mobile.evaluate('document.documentElement.scrollWidth <= innerWidth')
 mobile.locator('[data-node="A1"]').click();mobile.locator('#scenario-form').wait_for();mobile.screenshot(path=str(out/'veracity-v2-mobile.png'),full_page=True)
 checks.append('390px mobile graph and inspector render without horizontal overflow')
 browser.close()
assert not errors, errors
report={'passed':len(checks),'checks':checks,'browserErrors':errors,'mode':'Offline browser with actual server-generated records; browser fetch is a test double. Live browser network navigation was blocked by environment policy.','liveProviderCalls':0}
(out/'veracity-browser-qa.json').write_text(json.dumps(report,indent=2));print(json.dumps(report,indent=2))
